apiVersion: v1
kind: Service
metadata:
  name: e-commerce-order-service
spec:
  selector:
    app: e-commerce-order-app
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: e-commerce-product-service
spec:
  selector:
    app: e-commerce-product-app
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
